#!/usr/bin/env bash
#Transfer file from client to servers

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

if [ "$#" -le 2 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
elif [ "$#" -eq 3 ]
then
	scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
else
	scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
fi
