#!/usr/bin/env bash
#Install and configure nginx server
sudo apt update
sudo apt -y install nginx
sudo chown $USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
