#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Installation
sudo apt update && sudo apt upgrade
sudo apt install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt update
sudo apt -y haproxy install

# Configuration
sudo chown "$USER" /etc/default/haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo -e "\n# Set ENABLED to 1 if you want the init script to start haproxy.\nENABLED=1\n" >> /etc/default/haproxy
sudo chown "$USER" /etc/haproxy/haproxy.cfg
# sudo sed -e "s/http/tcp/" /etc/haproxy/haproxy.cfg
echo -e "\nfrontend frontend_app\n\tbind *:80\n\toption forwardfor\n\tdefault_backend web_server\n\nbackend web_server\n\tbalance roundrobin\n\tserver 89905-web-01 54.209.59.188:80 check\n\tserver 89905-web-02 3.94.213.103:80 check\n\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
