#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Installation
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*

# Configuration
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend my_web-backend\n\nbackend my_web-backend\n\tbalance roundrobin\n\tserver 89905-web-01 54.209.59.188:80 check\n\tserver 89905-web-02 3.94.213.103:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
