#!/usr/bin/env bash
# Pave a way for an nginx to listen at port 80
sudo lsof -t -i tcp:80 -s tcp:listen | sudo xargs kill
sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:8080/listen \[::\]:80/" /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" | sudo tee /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
