#!/usr/bin/env bash
# Pave a way for an nginx to listen at port 80
sudo lsof -t -i tcp:80 -s tcp:listen | sudo xargs kill
sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "s/ ipv6only=on//" /etc/nginx/sites-available/default
sudo service nginx start
