#!/usr/bin/env bash
# displays 'I am alive!' indefinitely.
while "true"
do
	echo "I am alive!" > /tmp/my_process
	sleep 2
done




cat > 101-manage_my_process && chmod u+x 101-manage_my_process
#!/usr/bin/env bash
# manages the daemons or background processes
. /lib/lsb/init-functions
start()
{
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
}
restart()
{
	./manage_my_process &
	rm -rf /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
}
stop()
{
	sudo kill -15 "cat /var/run/my_process.pid"
	rm -rf /var/run/my_process.pid
	echo "manage_my_process stopped"
}

case "$1" in
	start)
		start
		;;
	restart)
		restart
		;;
	stop)
		stop
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
