#!/usr/bin/env bash
# Graceful reload of gunicorn
sudo service gunicorn start
OLDPID=$(</run/AirBnB_clone_v4/AirBnB_clone_v4.pid)
kill -USR2 "$OLDPID"
sleep 1
timeout=5
while [[ "$timeout" -gt 0 ]]
do
    NEWPID=$(</run/AirBnB_clone_v4/AirBnB_clone_v4.pid) && kill -0 "$NEWPID"
    if [[ "$?" -eq 0 ]]
    then
      break
    else
      sleep 0.5
      (( timeout-- ))
    fi
done

echo "Success NEWPID = $NEWPID"
kill -WINCH "$OLDPID"
sleep 1
kill -TERM "$OLDPID"
sudo service gunicorn start
